// packages/demo/src/components/solid/CountInput.tsx
import { counter } from '../../counter'
import { nubbinSignal } from '@nubbins/solid'
import html from 'solid-js/html'

export const CountInput = () => {
  const [count, setCount] = nubbinSignal(counter)

  return html`
    <input
      type="number"
      value=${count}
      onInput=${(e: Event) =>
        setCount((e.currentTarget as HTMLInputElement).valueAsNumber)}
    />
  `
}

// packages/demo/src/components/preact/CountInput.tsx
/** @jsxImportSource preact */
import { counter } from '../../counter'
import { useNubbinSignal } from 'nubbins-preact'

export const CountInput = () => {
  const count = useNubbinSignal(counter)

  const handleChange = (e: Event) =>
    (count.value = (e?.currentTarget as HTMLInputElement).valueAsNumber)

  return <input type="number" value={count} onInput={handleChange} />
}
