// src/preact/components/CountInput.tsx
import { html } from 'htm/preact'
import { counter } from '../../counter'
import { useNubbinSignal } from '../useNubbinSignal'

export const CountInput = () => {
  const count = useNubbinSignal(counter)

  const handleChange = (e: Event) =>
    (count.value = (e?.currentTarget as HTMLInputElement).valueAsNumber)

  return html`<input type="number" value=${count} onInput=${handleChange} />`
}

// src/solid/components/CountInput.tsx
import { counter } from '../../counter'
import { datumSignal } from '../datumSignal'
import html from 'solid-js/html'

export const CountInput = () => {
  const [count, setCount] = datumSignal(counter)

  return html`
    <input
      type="number"
      value=${count}
      onInput=${(e: Event) =>
        setCount((e.currentTarget as HTMLInputElement).valueAsNumber)}
    />
  `
}
