// packages/react/src/components/CountInput.tsx
import { counter } from 'nubbins-common'
import { useNubbin } from '../useNubbin'

export const CountInput = () => {
  const [count, setCount] = useNubbin(counter)

  return (
    <input
      type="number"
      value={count}
      onChange={e => setCount(e.currentTarget.valueAsNumber)}
    />
  )
}

// packages/solid/src/components/CountInput.ts
import { counter } from 'nubbins-common'
import { nubbinSignal } from '../nubbinSignal'
import html from 'solid-js/html'

export const CountInput = () => {
  const [count, setCount] = nubbinSignal(counter)

  return html`
    <input
      type="number"
      value=${count}
      onInput=${(e: Event) =>
        setCount((e.currentTarget as HTMLInputElement).valueAsNumber)}
    />
  `
}
